name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Lint with pylint
      run: |
        pip install pylint
        # stop the build if there are Python syntax errors or undefined names
        pylint quantile_dotplot
    - name: Test with black
      run: |
        pip install black
        black --check .
